In [ ]:
AIM:- NAIVE BAYES ALGORITHM 
    Question 1:- Program to implement Naïve Bayes algorithm using any standard 
    dataset available in the public domain and find the accuracy of the 
    algorithm.

In [3]:
# AIM: Naïve Bayes Algorithm on Iris Dataset

import numpy as np 
from sklearn import datasets 
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score 

# Load the Iris dataset 
iris = datasets.load_iris() 
X = iris.data 
y = iris.target 

# Split the data into training and testing sets (80% training, 20% testing) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

# Create a Gaussian Naive Bayes classifier 
nb_classifier = GaussianNB() 

# Train the classifier using the training data 
nb_classifier.fit(X_train, y_train) 

# Make predictions on the testing data 
y_pred = nb_classifier.predict(X_test) 

# Calculate the accuracy of the classifier 
accuracy = accuracy_score(y_test, y_pred) 
print(f"Accuracy: {accuracy * 100:.2f}%") 

# Predict on a new sample 
new_sample = np.array([[5.1, 3.5, 1.4, 0.2]])  # Example flower

print("New sample shape:", new_sample.shape)
print("Model expects:", nb_classifier.n_features_in_, "features")

prediction = nb_classifier.predict(new_sample)
print("Prediction:", prediction)
print("Predicted class:", iris.target_names[prediction[0]])


Accuracy: 100.00%
New sample shape: (1, 4)
Model expects: 4 features
Prediction: [0]
Predicted class: setosa


In [ ]:
CODE 2 :- Program to implement Naïve Bayes algorithm with confusion matrix 
            using any standard dataset available in the public domain and find the 
            accuracy of the algorithm. 

In [4]:
# AIM: Naïve Bayes with Confusion Matrix and Accuracy using Iris Dataset

import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Gaussian Naive Bayes classifier
nb_classifier = GaussianNB()

# Train the classifier
nb_classifier.fit(X_train, y_train)

# Make predictions
y_pred = nb_classifier.predict(X_test)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Classification Report
class_report = classification_report(y_test, y_pred, target_names=iris.target_names)
print("Classification Report:\n", class_report)

# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy: 100.00%
